print("Rezept für Schokomuffins")
anzahl = int(input("Wie viele Muffins möchtest du backen? "))

mehl = round(18.75 * anzahl, 1)
kakaopulver = round(2.08 * anzahl, 1)
zucker = round(8.33 * anzahl, 1)
backpulver = round(1 * anzahl, 1)
vanillezucker = round(1.36 * anzahl, 1)
salz = round(0.17 * anzahl, 1)
neutralesOel = round(6.67 * anzahl, 1)
pflanzenmilch = round(18.75 * anzahl, 1)

print("Du benötigst folgende Zutaten: ")
print("________________________")
print("Trockene Zutaten:")
print(mehl, "g Mehl")
print(kakaopulver, "g Kakaopulver")
print(zucker, "g Zucker")
print(backpulver, "g Backpulver")
print(vanillezucker, "g Vanillezucker")
print(salz, "g Salz")
print("")
print("Feuchte Zutaten:")
print(neutralesOel, "g neutrales Öl")
print(pflanzenmilch, "g Sojamilch oder andere Pflanzenmilch")
print("________________________")
print("")

print("Du benötigst zusätzlich:")
print("________________________")
print("Muffinblech + Förmchen")
print("Rührschüssek")
print("Rührlöffel")
print("Küchenwaage/ Messbecher")
print("(Küchen-)Uhr")
print("________________________")
print("")

print("Vorgehen:")
print("________________________")
print("1. Backofen vorheizen auf 180 °C (Ober-Unterhitze).")
print("2. Papierförmchen in ein Muffinblech legen.")
print("3. In einer Rührschüssel die trockenen Zutaten mischen.")
print("4. Die trockenen Zutaten sehr gut miteinander vermischen.")
print("5. Feuchte Zutaten zufügen")
print("6. Mit einem Rührlöffel kurz gut umrühren. (Den Teig nicht lange rühren und dann sofort in die Förmchen füllen und backen. Der Ofen muss schon fertig vorgeheizt sein.)")
print("7. Den Teig in die 1 Papierförmchen im Muffinblech füllen.")
print("8. Im vorgeheizten Ofen bei 180 °C (Ober-Unterhitze) 25 Minuten backen.")
print("9. Stäbchenprobe machen und die fertigen Muffins abkühlen lassen.")
print("________________________")
